# Generated by Django 4.2 on 2024-03-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
