# Generated by Django 4.2 on 2023-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_module_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='module',
        ),
    ]
