# Generated by Django 4.2 on 2023-08-24 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_order_alter_module_order'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='code',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
