# Generated by Django 4.2 on 2023-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_rename_course_choice_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='page_html',
            new_name='text_html',
        ),
        migrations.AddField(
            model_name='choice',
            name='text_html',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='text_html',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
