# Generated by Django 4.2 on 2023-08-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0005_alter_answer_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='order',
        ),
    ]
