# Generated by Django 4.2 on 2023-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_answer_order_testcase_choice_testcase_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
