# Generated by Django 4.2 on 2023-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0010_choice_is_always_correct_choice_is_html_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='points',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='preserve_order',
            field=models.BooleanField(default=True),
        ),
    ]
