# Generated by Django 4.2 on 2024-01-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        ('step', '0014_remove_choicemulti_lesson_choice_is_multiple_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_multiple_choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='sample_size',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='ChoiceMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text_html', models.TextField()),
                ('is_always_correct', models.BooleanField(default=False)),
                ('preserve_order', models.BooleanField(default=True)),
                ('is_html_enabled', models.BooleanField(default=False)),
                ('is_options_feedback', models.BooleanField(default=False)),
                ('sample_size', models.PositiveSmallIntegerField(default=4)),
                ('points', models.FloatField(default=1)),
                ('full_answer', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerChoiceMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=512)),
                ('feedback', models.CharField(blank=True, max_length=512, null=True)),
                ('choice_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.choicemulti')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
