# Generated by Django 4.2 on 2024-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0015_remove_choice_is_multiple_choice_choice_sample_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': 'Тест _______ | Choice'},
        ),
        migrations.AlterModelOptions(
            name='choicemulti',
            options={'verbose_name_plural': 'Тест Мульти  | ChoiceMulti'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name_plural': 'Код ________ | Code'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name_plural': 'Текст ______ | Text'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Відео ______ | Video'},
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='choice',
            new_name='code',
        ),
        migrations.AddField(
            model_name='code',
            name='count_show_test',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='code',
            name='points',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_always_correct',
            field=models.BooleanField(default=False, verbose_name='is_always_correct | Всі відповіді правильні'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_html_enabled',
            field=models.BooleanField(default=False, verbose_name='is_html_enabled | Рендерити як HTML'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_options_feedback',
            field=models.BooleanField(default=False, verbose_name='is_options_feedback | Пояснення поруч з відповідями'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='points | Бали'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='preserve_order',
            field=models.BooleanField(default=True, verbose_name='preserve_order | Не виводити відповіді випадково'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='sample_size',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='sample_size | Розмір відповідей'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text_html',
            field=models.TextField(verbose_name='HTML контент | text_html'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='full_answer',
            field=models.BooleanField(default=True, verbose_name='full_answer | відповідь вірна за умови всіх відповідей'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='is_always_correct',
            field=models.BooleanField(default=False, verbose_name='is_always_correct | Всі відповіді правильні'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='is_html_enabled',
            field=models.BooleanField(default=False, verbose_name='is_html_enabled | Рендерити як HTML'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='is_options_feedback',
            field=models.BooleanField(default=False, verbose_name='is_options_feedback | Пояснення поруч з відповідями'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='points',
            field=models.FloatField(default=1, verbose_name='points | Бали'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='preserve_order',
            field=models.BooleanField(default=True, verbose_name='preserve_order | Не виводити відповіді випадково'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='sample_size',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='sample_size | Розмір відповідей'),
        ),
        migrations.AlterField(
            model_name='choicemulti',
            name='text_html',
            field=models.TextField(verbose_name='HTML контент | text_html'),
        ),
        migrations.AlterField(
            model_name='code',
            name='text_html',
            field=models.TextField(verbose_name='HTML контент | text_html'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_html',
            field=models.TextField(verbose_name='HTML контент | text_html'),
        ),
    ]
