# Generated by Django 4.2 on 2023-08-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_order_alter_module_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
