# Generated by Django 4.2 on 2023-08-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0009_alter_choice_lesson_alter_code_lesson_and_more'),
        ('course', '0005_remove_lesson_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
