# Generated by Django 4.2 on 2024-03-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_delete_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
