# Generated by Django 4.2 on 2024-01-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_delete_progresschoicemulti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresschoiceitem',
            name='index',
        ),
        migrations.AddField(
            model_name='progresschoice',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progresschoiceitem',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
