# Generated by Django 4.2 on 2024-01-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('step', '0015_remove_choice_is_multiple_choice_choice_sample_size_and_more'),
        ('progress', '0005_remove_progresschoiceitem_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressChoiceMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('solved', models.BooleanField(default=True)),
                ('repeat_task', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.choicemulti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressChoiceMultiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('solved', models.BooleanField(default=False)),
                ('answers_json', models.JSONField()),
                ('progress_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progresschoicemulti')),
            ],
        ),
    ]
