# Generated by Django 4.2 on 2024-01-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0013_rename_answer_answerchoice_answerchoicemulti'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresschoice',
            name='select_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.answerchoice'),
        ),
        migrations.AlterField(
            model_name='progresschoicemulti',
            name='select_answers',
            field=models.ManyToManyField(to='step.answerchoicemulti'),
        ),
    ]
