# Generated by Django 4.2 on 2023-12-10 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('step', '0011_choice_points_alter_choice_preserve_order'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresstext',
            name='points',
        ),
        migrations.AddField(
            model_name='progresstext',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProgressChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
