# Generated by Django 4.2 on 2024-01-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progresschoiceitem',
            old_name='data',
            new_name='answers_json',
        ),
    ]
