# Generated by Django 4.2 on 2023-12-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_progresstext_points_progresstext_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresschoice',
            name='solved',
            field=models.BooleanField(default=True),
        ),
    ]
