# Generated by Django 4.2 on 2024-01-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0013_rename_answer_answerchoice_answerchoicemulti'),
        ('progress', '0002_alter_progresschoice_select_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresschoice',
            name='order_answers',
        ),
        migrations.RemoveField(
            model_name='progresschoice',
            name='select_answer',
        ),
        migrations.AlterField(
            model_name='progresschoice',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProgressChoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_answers', models.CharField(max_length=256)),
                ('points', models.PositiveSmallIntegerField()),
                ('solved', models.BooleanField(default=False)),
                ('progress_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progresschoice')),
                ('select_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.answerchoice')),
            ],
        ),
    ]
