# Generated by Django 4.2 on 2024-01-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_rename_data_progresschoiceitem_answers_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progresschoiceitem',
            old_name='selected',
            new_name='index',
        ),
    ]
