# Generated by Django 4.2 on 2024-01-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_rename_selected_progresschoiceitem_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressChoiceMulti',
        ),
    ]
