# Generated by Django 4.2 on 2024-02-04 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('step', '0016_alter_choice_options_alter_choicemulti_options_and_more'),
        ('progress', '0007_remove_progresschoice_is_multiple_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('solved', models.BooleanField(default=True)),
                ('repeat_task', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressCodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('solved', models.BooleanField(default=False)),
                ('user_code', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('progress_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.progresscode')),
            ],
        ),
    ]
