# Generated by Django 4.2 on 2024-02-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_progresscode_progresscodeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresscodeitem',
            name='input',
        ),
        migrations.RemoveField(
            model_name='progresscodeitem',
            name='output',
        ),
    ]
