# Generated by Django 4.2 on 2023-08-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_rename_page_html_text_text_html_choice_text_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
