# Generated by Django 4.2 on 2023-08-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_testcase_remove_answer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testcase',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='step.code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='input',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
