# Generated by Django 4.2 on 2023-08-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0009_alter_choice_lesson_alter_code_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_always_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_html_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_options_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='preserve_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='sample_size',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
