# Generated by Django 4.2 on 2024-01-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        ('step', '0011_choice_points_alter_choice_preserve_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_multiple_choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='sample_size',
        ),
        migrations.CreateModel(
            name='ChoiceMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('text_html', models.TextField()),
                ('is_always_correct', models.BooleanField(default=False)),
                ('preserve_order', models.BooleanField(default=True)),
                ('is_html_enabled', models.BooleanField(default=False)),
                ('is_options_feedback', models.BooleanField(default=False)),
                ('sample_size', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
