# Generated by Django 4.2 on 2024-01-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0012_remove_choice_is_multiple_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerChoice',
        ),
        migrations.CreateModel(
            name='AnswerChoiceMulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=512)),
                ('feedback', models.CharField(blank=True, max_length=512, null=True)),
                ('choice_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.choicemulti')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
