# Generated by Django 4.2 on 2024-01-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0013_rename_answer_answerchoice_answerchoicemulti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicemulti',
            name='lesson',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AnswerChoiceMulti',
        ),
        migrations.DeleteModel(
            name='ChoiceMulti',
        ),
    ]
