# Generated by Django 4.2 on 2024-02-17 18:27

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0016_alter_choice_options_alter_choicemulti_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_html_test', django_quill.fields.QuillField()),
            ],
        ),
    ]
