# Generated by Django 4.2 on 2024-03-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0017_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='answerchoicemulti',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['order']},
        ),
    ]
